apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: cluster-in-existing-vpc-public-subnet
    region: us-east-1
vpc:
    subnets:
        public:
            us-easy-1a: {id: subnet-03d23b5f4535d48e8}
            us-easy-1b: {id: subnet-0d24c64fa5d828860}
nodeGroups:
    - name: eks-public-node
      instanceType: t2.micro
      desiredCapacity: 2
      labels: {role: workers}    