apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: cluster_in_existing_vpc
    region: us-east-1
vpc:
    subnets:
        private:
            us-east-1e: {id: subnet-010a359101a2362a0}
        public:
            us-easy-1a: {id: subnet-03d23b5f4535d48e8}
nodeGroups:
    - name: eks-node-01-public
      instanceType: t2.micro
      desiredCapacity: 1
      labels: {role: workers}
    - name: eks-node-02-private
      instanceType: t2.micro
      desiredCapacity: 1
      privateNetworking: true
      labels: {role: workers}      